### ISSUE TITLE
Some users match too many times

### ISSUE THREAD

**Issue by Erin-c** [cs50/compare50#26]
Some submissions match against multiple archives or current students and actually fill up a large amount of the 50 slots. Should we set some maximum that a user can match, maybe like 5 or so and have the be overwriteable with a command line flag?

@dmalan @crossroads1112 @Jelleas

**Comment by crossroads1112** [comment]
Working on a graphical view that should mitigate this issue somewhat. We also now weight rarer matches more heavily so this should help as well. It would be really nice to be able to test against a dataset that has this issue though @erin-c so if you could provide one that would be super helpful.
