### ISSUE TITLE
Bottom scrollbar doesn't disappear

### ISSUE THREAD

**Issue by Erin-c** [cs50/compare50#27]

**Comment by Erin-c** [comment]
Scrollbar obscures results
<img width="996" alt="scrollbar" src="https://user-images.githubusercontent.com/16881882/56902260-e5bc2800-6a67-11e9-8e40-de57af22c4b8.png">

**Comment by Jelleas** [comment]
Seems to be an issue of Chrome on OS X specifically: <https://stackoverflow.com/questions/54711387/macos-chrome-horizontal-scrollbar-not-disappearing>

We can, and maybe should regardless of this issue, pad the bottom of every file to account for the scrollbar. Implemented this in 3b9117a so there is no overlap between scrollbar and code.
