### ISSUE TITLE
english_dictionary.txt has 600 permissions instead of 644

### ISSUE THREAD

**Issue by dmalan** [cs50/compare50#31]
```
$ cli50
$ sudo pip install compare50
$ ls -l /usr/local/lib/python3.7/site-packages/compare50/comparators/
total 1436
-rw-r--r-- 1 root root      74 Aug  7 13:06 __init__.py
drwxr-xr-x 2 root root    4096 Aug  7 13:06 __pycache__/
-rw-r--r-- 1 root root    4078 Aug  7 13:06 _misspellings.py
-rw-r--r-- 1 root root   13639 Aug  7 13:06 _winnowing.py
-rw------- 1 root root 1439228 Aug  7 13:06 english_dictionary.txt
```

**Comment by crossroads1112** [comment]
Hmm... I can't seem to replicate this. <img src="https://i.imgur.com/Qwwhs48.png"/>

**Comment by FeruzOripov** [comment]
Interesting, I have just installed and It looks good.

`.rw-r--r--    74 feruz 12 Aug 20:18  __init__.py
drwxr-xr-x     - feruz 12 Aug 20:18  __pycache__
.rw-r--r--  4.1k feruz 12 Aug 20:18  _misspellings.py
.rw-r--r--   13k feruz 12 Aug 20:18  _winnowing.py
.rw-r--r--  1.4M feruz 12 Aug 20:18  english_dictionary.txt`

**Comment by FeruzOripov** [comment]
Maybe this is caused by `sudo` command. It is safer to not install `pip` packages using `sudo`.
