### ISSUE TITLE
does compare50 ignore binary files?

### ISSUE THREAD

**Issue by kzidane** [cs50/compare50#41]

**Comment by Jelleas** [comment]
We try to ignore them:

https://github.com/cs50/compare50/blob/6c9d3f7b193ccd6b541aed556e8d4319dc12fb9e/compare50/__main__.py#L72-L80

**Comment by kzidane** [comment]
Should we ignore before even reading? :)

**Comment by Jelleas** [comment]
But then how would you know it's a binary? This just tries to read it, and abandons if it fails.

**Comment by kzidane** [comment]
I should've been more clear. I meant perhaps by inferring from the file's extension or perhaps checking it it has a magic number or something instead of reading the entire file and trying to decode it. The use case here is that the submissions for one of the problems has `png`, `ttf`, and `wav` files and compare50 is significantly slower when run on these submissions with these files being part of them. You could argue that users should remove such files before running compare50, but it'd be nice if compare50 can handle this if possible.

**Comment by Jelleas** [comment]
Oh! Totally valid usecase. There is a guess mimetypes function that does all this and is probably faster than what we do. We ultimately decided against it because this approach was more robust and simpler, but if performance is an issue we should perhaps switch.

**Comment by crossroads1112** [comment]
Yeah, we could use `libmagic` (via `python-magic`) like style50 does (the same library that the file command uses), but it's not necessarily easy to install on Windows (and has to be installed manually on Mac). 

Another option would be to read some small number of bytes first e.g. adding an initial `f.read(100)` to the beginning. The probability that a binary file begins with 100 utf8 characters is probably pretty small for most kinds of binary files (it's certainly true for randomly generated files and executables), so this could be a decent heuristic.

**Comment by crossroads1112** [comment]
Something like this:

```
try:
   blocksize = 64
    chars = []
    nchars = 1
    c = f.read(blocksize)
    while c:
        chars.append(c)
        blocksize *= 2 # every time we read a block correctly, the probability that this is a valid file increases
        c = f.read(blocksize)
except UnicodeDecodeError:
    ...

```

would also work, though it'd be somewhat slower for valid files (since you're doing `log2(fileSize)` read calls instead of 2 in the previous solution). The advantage here would be that we'd potentially avoid reading all of a bad file even if the first 100 characters were valid.
