### ISSUE TITLE
Null Interval objects not allowed in IntervalTree

### ISSUE THREAD

**Issue by kzidane** [cs50/compare50#42]
It appears that markdown code blocks mess up compare50's span ranges because the starting index of some tokens is reset when a new code block ( \`\`\`LANGUAGE) is encountered (presumably because the tokenizer wants to think of separate code blocks as separate source files). For example:

**a/foo.md:**
```
    ```lua
    local push = require "push"

    local gameWidth, gameHeight = 1080, 720 --fixed game resolution
    local windowWidth, windowHeight = love.window.getDesktopDimensions()

    push:setupScreen(gameWidth, gameHeight, windowWidth, windowHeight, {fullscreen = true})

    function love.draw()
      push:start()
  
      --draw here
  
      push:finish()
    end
    ```
    ```lua
    local push = require "push"

    local gameWidth, gameHeight = 1080, 720 --fixed game resolution
    local windowWidth, windowHeight = love.window.getDesktopDimensions()
    windowWidth, windowHeight = windowWidth*.7, windowHeight*.7 --make the window a bit 
    smaller than the screen itself

    push:setupScreen(gameWidth, gameHeight, windowWidth, windowHeight, {fullscreen = false})

    function love.draw()
      push:start()
  
      --draw here
  
      push:finish()
    end
    ```
```

**b/foo.md:**
```
    ```lua
    local push = require "push"

    local gameWidth, gameHeight = 1080, 720 --fixed game resolution
    local windowWidth, windowHeight = love.window.getDesktopDimensions()

    push:setupScreen(gameWidth, gameHeight, windowWidth, windowHeight, {fullscreen = true})

    function love.draw()
      push:start()
      
      --draw here
      
      push:finish()
    end
    local push = require "push"

    local gameWidth, gameHeight = 1080, 720 --fixed game resolution
    local windowWidth, windowHeight = love.window.getDesktopDimensions()
    windowWidth, windowHeight = windowWidth*.7, windowHeight*.7 --make the window a bit smaller than the screen itself

    push:setupScreen(gameWidth, gameHeight, windowWidth, windowHeight, {fullscreen = false})

    function love.draw()
      push:start()
      
      --draw here
      
      push:finish()
    end
    ```
```

Running compare50 on these produces the following:
```
$ compare50 --passes structure --verbose a/foo.md b/foo.md
...
Sorry, something's wrong! Let sysadmins@cs50.harvard.edu know!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/compare50/__main__.py", line 351, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/compare50/__main__.py", line 340, in main
    pass_to_results[pass_] = _api.compare(scores, ignored_files, pass_)
  File "/usr/local/lib/python3.7/site-packages/compare50/_api.py", line 76, in compare
    for comparison in pass_.comparator.compare(scores, ignored_files):
  File "/usr/local/lib/python3.7/site-packages/compare50/comparators/_winnowing.py", line 133, in compare
    span_matches += _api.expand(index_a.compare(index_b), tokens_a, tokens_b)
  File "/usr/local/lib/python3.7/site-packages/compare50/_api.py", line 231, in expand
    span_tree_a.addi(new_span_a.start, new_span_a.end)
  File "/usr/local/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 330, in addi
    return self.add(Interval(begin, end, data))
  File "/usr/local/lib/python3.7/site-packages/intervaltree/intervaltree.py", line 313, in add
    " {0}".format(interval)
ValueError: IntervalTree: Null Interval objects not allowed in IntervalTree: Interval(335, 173)

```

**Comment by crossroads1112** [comment]
I can't replicate this. When I run `compare50` on these files it tokenizes them as expected and doesn't display this error.

**Comment by kzidane** [comment]
I should've pip froze. Maybe it was a bug in one of the libraries. Thanks for looking into it!

**Comment by joelverg** [comment]
how did you fix this?

**Comment by kzidane** [comment]
Are you able to reproduce this issue, @joelverg?

**Comment by joelverg** [comment]
I have different issue, about the debug, but we have same output, traceback of files

**Comment by crossroads1112** [comment]
@joelverg would you be willing to send a zip of the files (anonymized if need be) causing this error along with the output of `pip3 freeze` to sysadmins@cs50.harvard.edu?
