### ISSUE TITLE
In render_#.html, add feature to POST side-by-side files to render.cs50.io

### ISSUE THREAD

**Issue by dmalan** [cs50/compare50#61]
At the moment, this might need to be done with Ajax in order to POST both files as File objects, https://cs50.readthedocs.io/render/, as by creating them from Strings first.

**Comment by jsarchibald** [comment]
In progress - render50 function is finished on [a working branch](https://github.com/jsarchibald/compare50/blob/render50-pdf/compare50/_renderer/static/match.js#L444) but integration is pending the switch to React.

**Comment by jsarchibald** [comment]
Resolved by #81. There's a PDF button in the React site that will POST to render.cs50.io and download the result.
