### ISSUE TITLE
Scrolling when clicking "next" is out of sync

### ISSUE THREAD

**Issue by brianyu28** [cs50/compare50#62]
When clicking "Next" in match_#.html, the left side scrolls to the next match more quickly than the right side scrolls. Not sure if that's intentional or not, but for scanning matches quickly it would be more efficient if both matches scrolled at the same time.

**Comment by Jelleas** [comment]
It is intentional, the right starts scrolling after the left side has finished. Mostly to give your eyes some time to see where you're jumping to in the code. I can experiment with this a bit more, but if I remember correctly it wasn't too easy to keep track of things if both sides start scrolling.

**Comment by brianyu28** [comment]
Ah, good to know, thanks!
