### ISSUE TITLE
Clusters highlight together even when no longer a cluster

### ISSUE THREAD

**Issue by brianyu28** [cs50/compare50#63]
If a set of submissions forms a large cluster, and the threshold increases such that the cluster breaks up into smaller clusters, hovering over one of the submissions still highlights all of the submissions in the original cluster rather than the new smaller one. This is usually not ideal because the original cluster is often very large and therefore not too meaningful, since the threshold starts low.

![Screen Shot 2020-07-13 at 11 29 47 AM](https://user-images.githubusercontent.com/16066224/87323027-33ea0980-c4fc-11ea-8254-880632f1008d.png)

**Comment by Jelleas** [comment]
This is bit of a tricky design question. Because changing colors makes it tricky to keep track of what happened when you moved the slider.

**Comment by brianyu28** [comment]
Working with compare50 again this summer, I think you're right that keeping the colors consistent on slider change is clearer than changing the colors as the slider moves, so closing this for now.
