### ISSUE TITLE
Soft-wrap long lines instead of using overflow-x auto?

### ISSUE THREAD

**Issue by dmalan** [cs50/compare50#75]
For assignments with SQL, whether standalone statements or embedded in Python code, lines tend to get rather long, and left-right scrolling becomes rather inefficient. Perhaps better to soft-wrap by default? And/or add a toggle for turning it on/off?

**Comment by Jelleas** [comment]
Implemented in https://github.com/cs50/compare50/projects/4

![softwrap](https://user-images.githubusercontent.com/1257775/88444526-d9b34780-ce1d-11ea-8998-460d3e4340bc.gif)

**Comment by dmalan** [comment]
Awesome, thanks!
